// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrmnjozgnuwikbjomrra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZybW5qb3pnbnV3aWtiam9tcnJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODYzNTEsImV4cCI6MjA2NzY2MjM1MX0.myv14UBTR7OwhNYQiQIrNc5ha8TjF3WNiXlAo3iG1yA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});